name: CI
on:
  push:
    branches:
      - "main"


jobs:
  tests:
    runs-on:
      - ubuntu-latest   
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: 1.18.x

        - name: Run tests
          run: make run